audio:
 chunk_size: 123480 # (44100 * 2.8 seconds)
 min_mean_abs: 0.001

datas:
  codec_type: mp3
  codec_options:
    bitrate: random
    compression: random
    complexity: random
    vbr: random
  sr: 44100

model:
  sr: 44100
  win: 20 # ms
  feature_dim: 256
  layer: 6

discriminator:
  nch: 2 # Number of audio channels
  window: [32, 64, 128, 256, 512, 1024, 2048]

optimizer_g:
  name: adamw
  lr: 0.001
  weight_decay: 0.01

optimizer_d:
  name: adamw
  lr: 0.0001
  weight_decay: 0.01
  betas: [0.5, 0.99]

scheduler_g:
  name: ReduceLROnPlateau 
  mode: max
  patience: 20
  factor: 0.5 

scheduler_d:
  name: ReduceLROnPlateau 
  mode: max
  patience: 20
  factor: 0.5

loss_g:
  eps: 1.0e-8
loss_d:
  eps: 1.0e-8

training:
  batch_size: 2 
  gradient_accumulation_steps: 1
  grad_clip: 5.0
  patience: 20
  reduce_factor: 0.5 # Ensure this matches scheduler if ReduceLROnPlateau used
  num_epochs: 500
  num_steps: 50 
  q: 0.95
  coarse_loss_clip: True # Default for masked loss
  use_amp: True
  is_gan: True
  lr: 0.001 

inference:
  batch_size: 1
  num_overlap: 2
  normalize: False